// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mlssjmlbaaonuuietjbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1sc3NqbWxiYWFvbnV1aWV0amJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg5MTk2ODcsImV4cCI6MjA1NDQ5NTY4N30.i_TZ-Jx9sDw1u-x_qEwua-RcljRk3chca-rp5XgjYQ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);